### ISSUE TITLE
No Drill file for this one?

### ISSUE THREAD

**Issue by nrayner** [consolesunleashed/nintendo-64-av-multiout-breakout-pcb#1]
I submitted this to jlcpcb to be made and got a message about there not being a drill file:

1.Hi Sir/ Madam, There are no drill in your file, please kindly check!You can click ‘Replace file’ button to re-upload the file in your JLCPCB account page .Thanks

**Comment by consolesunleashed** [comment]
Hi. Was a mistake. I've added it now. Cheers
